#cloud-config

package_update: true

package_upgrade: true

runcmd:
  - snap install bitcoin-core
  - echo '#bitcoin-core alias' >> /home/ubuntu/.bashrc
  - echo alias bitcoind='bitcoin-core.daemon' >> /home/ubuntu/.bashrc
  - echo alias bitcoin-cli='bitcoin-core.cli' >> /home/ubuntu/.bashrc
  - echo alias cli=bitcoin-cli >> /home/ubuntu/.bashrc
  - reboot

bootcmd:
  - su -c 'bitcoind -daemon -server=1 -testnet=1' - ubuntu 